let coloursTheme = {
    primary: "#29518E",
    accent: "#EA7A2D",
    white: "#ffffff",
    backgroundColor: "#FFFFFF",
    backgroundAltColor: "#000000",
    buttonBorderColor: "#000000",
    mainButtonColor:"#5b6670",
    mainButtonFontColor:"#FFFFFF",
    fontColor: "#000000",
    fontColorAlt: "#FFFFFF",
    errorFontColor:'#EA7A2D',
    secondaryColor:"#EA7A2D",
    secondaryButtonFontColor: "#FFFFFF",
    secondaryButtonColor:"#EA7A2D",
    focusedIcon:"#33A3F4",
    unfocusedIcon:"#949494",
    lightGrey: "#E8E8E8",
    errorRed: "#F0040B",
    warning: "#EFCE4A",
    warningDark: "#C8A61D",
    successGreen: "#04B806",
    borderColor: "#EFEFEF",
    textGrey: "#B0B0B0",
    textDarkGrey: "#7B7B7B",
    green:"#197a21",
    blue:"#193f7a",
    yellow:"#f4d041"
};

export const colours = coloursTheme;